name: Build caddy-linux-amd64

on:
  push:
    paths:
      - 'caddy-linux-amd64.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install go
      uses: actions/setup-go@master
    
    - name: Install xcaddy
      run: go get -v github.com/caddyserver/xcaddy/cmd/xcaddy@latest

    - name: build caddy
      run: |
        export GOARCH=amd64
        export GOOS=linux
        ./xcaddy build \
          --with github.com/caddy-dns/cloudflare \
          --with github.com/caddy-dns/alidns \
          --with github.com/clevergo/caddy-dnspodcn \
          --with github.com/caddy-dns/dnspod \
          --with github.com/lucaslorentz/caddy-docker-proxy/plugin/  \
          --with github.com/mholt/caddy-l4  \
          --with github.com/mastercactapus/caddy2-proxyprotocol \
          --with github.com/mholt/caddy-webdav  \
          --with github.com/caddyserver/forwardproxy@caddy2  \
          --with github.com/imgk/caddy-trojan  

    - name: upload
      uses: actions/upload-artifact@master
      with:
        name: caddy-linux-amd64
        path: ./caddy
